FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY packages/database/prisma ./prisma/
RUN npm ci

COPY apps/api ./apps/api
COPY packages ./packages
COPY turbo.json tsconfig.json ./

EXPOSE 3004

CMD ["npm", "run", "dev:api"]
