FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY apps/admin-panel ./apps/admin-panel
COPY packages ./packages
COPY turbo.json tsconfig.json ./

EXPOSE 3001

CMD ["npm", "run", "dev:admin"]
