FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY apps/marketing-site ./apps/marketing-site
COPY packages ./packages
COPY turbo.json tsconfig.json ./

EXPOSE 3000

CMD ["npm", "run", "dev:marketing"]
